//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMart_Website.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.Bill_List = new HashSet<Bill_List>();
            this.BranchImport_List = new HashSet<BranchImport_List>();
            this.HeadImport_List = new HashSet<HeadImport_List>();
            this.PriceHistories = new HashSet<PriceHistory>();
            this.Promotions = new HashSet<Promotion>();
            this.requestImport_List = new HashSet<requestImport_List>();
        }
    
        public int IDProduct { get; set; }
        public string Name { get; set; }
        public string Image { get; set; }
        public string IDType { get; set; }
        public string IDSupplier { get; set; }
    
        public virtual ICollection<Bill_List> Bill_List { get; set; }
        public virtual ICollection<BranchImport_List> BranchImport_List { get; set; }
        public virtual ICollection<HeadImport_List> HeadImport_List { get; set; }
        public virtual ICollection<PriceHistory> PriceHistories { get; set; }
        public virtual ProductType ProductType { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual ICollection<Promotion> Promotions { get; set; }
        public virtual ICollection<requestImport_List> requestImport_List { get; set; }
    }
}
